---

- name:Set hostname
  hostname: name={{inventory_hostname}}

- name:Install yum packages
  yum: name={{yum_packages}} state=present

- name:Install node
  shell: "wget -qO- {{node_repo}} | sh"
  yum: name=nodejs state=latest
